/*  
 *  Programación y diseño orientado a objetos
 *  Grado en Ingeniería Informática
 * 
 *  2013 © Copyleft - All Wrongs Reserved
 *
 *  Ernesto Serrano <erseco@correo.ugr.es>
 * 
 */
package gui;

import napakalaki.BadStuff;

public class BadStuffView extends javax.swing.JPanel {

    private BadStuff badStuffModel;
    
    public void setBadStuff (BadStuff t) {
        
        badStuffModel = t;

        String badStuffText = "<html>" +badStuffModel.getText() + "</html>";
        
        lblText.setText(badStuffText);
        //lblLevels.setText(Integer.toString(badStuffModel.getLevels()));

        //lblGoldCoins.setText(Integer.toString(badStuffModel.getGoldCoins()));
        
        //lblTreasureKind.setText(badStuffModel.getType().toString());

       
        
       

        //Finalizar con la siguiente orden para que los cambios se hagan efectivos
        repaint();
}
    
    /**
     * Creates new form TreasureView
     */
    public BadStuffView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        lblText.setText("<html>Te atrapan para llevarte de fiesta y te dejan caer en mitad del vuelo. Descarta 1 mano visible y 1 mano oculta</html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
