/*  
 *  Programación y diseño orientado a objetos
 *  Grado en Ingeniería Informática
 * 
 *  2013 © Copyleft - All Wrongs Reserved
 *
 *  Ernesto Serrano <erseco@correo.ugr.es>
 *  Noureddine El Alaoui <nourdine@correo.ugr.es>
 *
 *  NOTA: Esta es una implementación del dado para integrarla como un control
 *  en el formulario pero actualmente no se está utilizando
 * 
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author Ernesto Serrano <erseco@correo.ugr.es>
 */
public class DiceView extends javax.swing.JPanel {

    private Random generator = new Random();
    private Timer timerDice;
    private int value;
    
    
    private int privateNextNumber() {
        return (generator.nextInt(6) + 1);
    }
    private ActionListener diceAction = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ev) {
            value = privateNextNumber();
            lblDice.setText(Integer.toString(value));
            
            
        }
    };
    
    public int nextNumber() {
        return nextNumber("Puedes llamar al método",
                "Pasándole 2 cadenas como parámetros");

    }

    public int nextNumber(String message1, String message2) {
        
        timerDice.start();
        
        
        return value;
    }

    public void SetDice() {
    
        
    
    
    }
    
    /**
     * Creates new form DiceView
     */
    public DiceView() {
        initComponents();
        
         timerDice = new Timer(50, diceAction);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDice.setBackground(new java.awt.Color(255, 255, 255));
        lblDice.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lblDice.setText("6");
        lblDice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiceMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblDice)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblDice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiceMouseClicked
        // TODO add your handling code here:
        
        timerDice.stop();
        
    }//GEN-LAST:event_lblDiceMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDice;
    // End of variables declaration//GEN-END:variables
}
