/*  
 *  Programación y diseño orientado a objetos
 *  Grado en Ingeniería Informática
 * 
 *  2013 © Copyleft - All Wrongs Reserved
 *
 *  Ernesto Serrano <erseco@correo.ugr.es>
 *  Noureddine El Alaoui <nourdine@correo.ugr.es>
 * 
 */
package gui;

import napakalaki.Monster;

public class MonsterView extends javax.swing.JPanel {

    private Monster monsterModel;
    
    public void setMonster (Monster t) {
        
        monsterModel = t;

        lblName.setText(monsterModel.getName());
        
        String bonusText = Integer.toString(monsterModel.getBasicValue()) + "/" + Integer.toString(monsterModel.getSpecialValue());
        
        lblBonus.setText(bonusText);
        

        //lblGoldCoins.setText(Integer.toString(monsterModel.getGoldCoins()));

        //lblTreasureKind.setText(monsterModel.getType().toString());

        this.badStuffView1.setBadStuff(t.getBadStuff());
        this.prizeView1.setPrize(t.getPrize());

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(monsterModel.getIcon())));
        

        //Finalizar con la siguiente orden para que los cambios se hagan efectivos
        repaint();
}
    
    /**
     * Creates new form TreasureView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        prizeView1 = new gui.PrizeView();
        badStuffView1 = new gui.BadStuffView();
        lblImage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Monstruo"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Nombre Monstruo");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 130, -1));

        lblBonus.setText("0");
        add(lblBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        prizeView1.setAlignmentX(0.0F);
        prizeView1.setAlignmentY(0.0F);
        prizeView1.setFocusable(false);
        prizeView1.setMaximumSize(null);
        prizeView1.setMinimumSize(null);
        prizeView1.setPreferredSize(null);
        add(prizeView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        add(badStuffView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 100));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/monsters/01.png"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.BadStuffView badStuffView1;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private gui.PrizeView prizeView1;
    // End of variables declaration//GEN-END:variables
}
