/*  
 *  Programación y diseño orientado a objetos
 *  Grado en Ingeniería Informática
 * 
 *  2013 © Copyleft - All Wrongs Reserved
 *
 *  Ernesto Serrano <erseco@correo.ugr.es>
 *  Noureddine El Alaoui <nourdine@correo.ugr.es>
 * 
 */
package gui;

import javax.swing.JOptionPane;
import napakalaki.CombatResult;
import napakalaki.Napakalaki;

public class NapakalakiView extends javax.swing.JFrame {

    private Napakalaki napakalakiModel;

    public void setNapakalaki(Napakalaki model) {

        this.napakalakiModel = model;

        this.playerView.setNapakalaki(model, this);

        this.playerView.setPlayer(model.getCurrentPlayer());
        this.monsterView.setMonster(model.getCurrentMonster());




        //Finalizar con la siguiente orden para que los cambios se hagan efectivos
        repaint();

    }
    
    public void checkPendingBadStuff() {
        
//        if (this.napakalakiModel.getCurrentPlayer().validState()){
//         this.btNextTurn.setEnabled(true);
//        } 
        
    
        if (!this.btCombat.isEnabled() && this.napakalakiModel.nextTurnAllowed()) {
        
           
                 this.btNextTurn.setEnabled(true);

        }
    
    }

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView = new gui.MonsterView();
        playerView = new gui.PlayerView();
        btCombat = new javax.swing.JButton();
        btNextTurn = new javax.swing.JButton();
        lblCombatResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Napakalaki");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(monsterView, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 180, 340));

        playerView.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                playerViewPropertyChange(evt);
            }
        });
        getContentPane().add(playerView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        btCombat.setText("Combatir");
        btCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCombatActionPerformed(evt);
            }
        });
        getContentPane().add(btCombat, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        btNextTurn.setText("Siguiente turno");
        btNextTurn.setEnabled(false);
        btNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextTurnActionPerformed(evt);
            }
        });
        getContentPane().add(btNextTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        lblCombatResult.setText("Resultado del combate:");
        getContentPane().add(lblCombatResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCombatActionPerformed

        this.btCombat.setEnabled(false);
        checkPendingBadStuff();
        
        
        CombatResult result = napakalakiModel.developCombat();

        String combatresultText = "<html>Resultado del combate:<br />" + result.toString() + "</html>";
        
        this.lblCombatResult.setText(combatresultText);

        this.setNapakalaki(napakalakiModel);

        if (result == CombatResult.WinAndWinGame) {

            JOptionPane.showMessageDialog(null, "El jugador " + this.napakalakiModel.getCurrentPlayer().getName() + " ha llegado al nivel 10");
            System.exit(0);
        }

    }//GEN-LAST:event_btCombatActionPerformed

    private void btNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextTurnActionPerformed

        this.btCombat.setEnabled(true);
        this.btNextTurn.setEnabled(false);
        
        this.napakalakiModel.nextTurn();

        this.setNapakalaki(napakalakiModel);

    }//GEN-LAST:event_btNextTurnActionPerformed

    private void playerViewPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_playerViewPropertyChange
        // TODO add your handling code here
    }//GEN-LAST:event_playerViewPropertyChange

    /**
     * @param args the command line arguments
     */
    public void showView() {
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCombat;
    private javax.swing.JButton btNextTurn;
    private javax.swing.JLabel lblCombatResult;
    private gui.MonsterView monsterView;
    private gui.PlayerView playerView;
    // End of variables declaration//GEN-END:variables
}
