/*  
 *  Programación y diseño orientado a objetos
 *  Grado en Ingeniería Informática
 * 
 *  2013 © Copyleft - All Wrongs Reserved
 *
 *  Ernesto Serrano <erseco@correo.ugr.es>
 *  Noureddine El Alaoui <nourdine@correo.ugr.es>
 * 
 */
package gui;

import napakalaki.Treasure;

public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    private boolean selected = false;

    public boolean isSelected() {

        return this.selected;

    }

    public Treasure getTreasure() {

        return this.treasureModel;

    }

    public void setTreasure(Treasure t) {

        treasureModel = t;

        String nameText = "<html>" + treasureModel.getName() + "</html>";
        
        lblName.setText(nameText);
        
        
        String bonusText = Integer.toString(treasureModel.getBasicValue()) + "/" + Integer.toString(treasureModel.getSpecialValue());
        
        lblBonus.setText(bonusText);
        
        String goldCoinsText = "$" + Integer.toString(treasureModel.getGoldCoins());

        lblGoldCoins.setText(goldCoinsText);

        lblTreasureKind.setText(treasureModel.getType().toString());
        
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(treasureModel.getIcon())));
        
        //Forzamos una llamada al evento para que se cambie el color
        formMouseClicked(null);

        //Finalizar con la siguiente orden para que los cambios se hagan efectivos
        repaint();
    }

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblTreasureKind = new javax.swing.JLabel();
        lblGoldCoins = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(new java.awt.Color(0, 204, 0));
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(140, 220));
        setSize(new java.awt.Dimension(137, 216));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblName.setText("<html>Clavo de rail ferroviario</html>");
        lblName.setToolTipText("");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 88, 30));

        lblBonus.setText("0/0");
        add(lblBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTreasureKind.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTreasureKind.setText("PRUEBA");
        add(lblTreasureKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 180, 80, -1));

        lblGoldCoins.setText("$200");
        add(lblGoldCoins, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/treasures/01.png"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        this.selected = !this.selected;

        setOpaque(this.selected);

        this.repaint();
//        if (this.selected) {
//        
//            
//        
//            this.selected = false;
//        } else {
//        
//
//           
//            this.selected = true;
//        }



    }//GEN-LAST:event_formMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblGoldCoins;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTreasureKind;
    // End of variables declaration//GEN-END:variables
}
